### ISSUE TITLE
[ESPAÇOS] Dropdown de "Tipo de espaço" não está em ordem alfabética

### ISSUE THREAD

**Issue by emillecatarine** [RedeMapas/mapas#101]
**Contexto:** Na página Espaços, quando abro a modal "Criar Espaço", o dropdown "Selecione o tipo do espaço" não está ordenado alfabeticamente. Por serem muitas opções, facilitaria para o usuário se a ordem alfabética (A–Z) fosse adotada.
**Ocorrência:** desktop e mobile
**Recomendação:** Ordenar itens do dropdown "Selecione o tipo do espaço" alfabeticamente (A–Z).

**Comment by LeonardoZanotti** [comment]
![名称未設定](https://github.com/user-attachments/assets/0208da6f-ac84-4fc6-a84a-60274e4a23e4)

Tipos de espaço agora estão aparecendo em ordem alfabética.

Pull request: FIX - dropdown de Tipos de espaço agora aparecem em ordem alfabética #304
