### ISSUE TITLE
[ESPAÇOS] Indicativo de quantidade de resultados encontrados parece um botão

### ISSUE THREAD

**Issue by emillecatarine** [RedeMapas/mapas#109]
**Contexto:** Na tela de resultados de “Espaços”, o texto “X Espaços encontrados” com o fundo branco faz parecer que é um botão.
**Ocorrência:** desktop
**Recomendação:** Retirar o fundo branco.

<img width="886" alt="image" src="https://github.com/LabCDBr/gestao/assets/95487110/d9f8bbe2-d794-4556-b685-d8c5e415dbd6">

**Comment by LeonardoZanotti** [comment]
![image](https://github.com/user-attachments/assets/4be38030-9d58-4491-af7d-5d2768c59f41)
Resolvido neste PR: FIX - indicativo de resultados da search #326
