### ISSUE TITLE
[ESPAÇOS] Aplicar cor de link nos link do Espaço

### ISSUE THREAD

**Issue by emillecatarine** [RedeMapas/mapas#110]
**Contexto:** Na página de detalhes do Espaço, o link do espaço está sendo apresentado em preto. Mesmo com o ícone de link ao lado, ficaria mais claro se o próprio link tivesse a cor de link aplicada.
**Ocorrência:** desktop e mobile
**Recomendação:** Aplicar cor de link no link do espaço (corresponde ao preenchimento do campo “Link para página ou site do espaço”).

<img width="1211" alt="image" src="https://github.com/LabCDBr/gestao/assets/95487110/166fab99-dcfa-4464-bdb7-52f48777c2e4">

**Comment by LeonardoZanotti** [comment]
![image](https://github.com/user-attachments/assets/5d01cf20-2332-4fa9-a298-7906323d0a3e)

Resolvido no PR: FIX - altera estilo do link do espaco #327
