### ISSUE TITLE
[ESPAÇOS] Quebra de linha cortando palavras

### ISSUE THREAD

**Issue by emillecatarine** [RedeMapas/mapas#111]
**Contexto:** No card do Espaço (na página de busca de Espaços) e na página de detalhes do Espaço, a quebra de linha da descrição do Espaço está cortando a palavra (por exemplo, na minha tela cortou Dis-trito).
**Ocorrência:** desktop e mobile
**Recomendação:** É preciso ajustar para que palavras que não caibam inteira em uma linha sejam apresentadas completas na linha seguinte.

<img width="865" alt="Captura de Tela 2024-04-18 às 08 28 23" src="https://github.com/LabCDBr/gestao/assets/95487110/265ecfbb-1b56-4e15-b310-1829c5a2b3d4">

<img width="1256" alt="image" src="https://github.com/LabCDBr/gestao/assets/95487110/492ceed9-f3fa-4711-bdbd-43632dc56d1c">

**Comment by LeonardoZanotti** [comment]
![Screenshot from 2024-08-20 09-31-55](https://github.com/user-attachments/assets/53fb6d0e-649d-4de7-988a-539ef5d2cf12)

Não consegui reproduzir, mesmo testando com vários tipos de textos, palavras compridas e curtas.
