### ISSUE TITLE
[ESPAÇOS] Tooltip do mapa não apresenta conteúdo

### ISSUE THREAD

**Issue by emillecatarine** [RedeMapas/mapas#116]
**Contexto:** Na visualização dos Espaços pelo mapa, existe a opção de clicar no Espaço para visualizar uma tootltip com informações. A tooltip não está apresentando informação alguma.
**Ocorrência:** desktop e mobile
**Recomendação:** Corrigir bug.

<img width="459" alt="Captura de Tela 2024-04-18 às 08 19 38" src="https://github.com/LabCDBr/gestao/assets/95487110/924e8215-75d4-486e-ba1e-839325bc1169">

**Comment by LeonardoZanotti** [comment]
Desktop:
![image](https://github.com/user-attachments/assets/b87fcfda-009e-406a-822b-f1a4da437c77)
Mobile:
![image](https://github.com/user-attachments/assets/9225a824-2ff0-4be1-ab21-c874c8e528d2)

Não consegui reproduzir o bug. Favor verificar se ainda está ocorrendo.
