### ISSUE TITLE
[OPORTUNIDADES] Fases de avaliação da oportunidade não aparecem

### ISSUE THREAD

**Issue by emillecatarine** [RedeMapas/mapas#168]
**Ocorrência:** desktop e mobile
**Contexto:** Quando crio uma nova oportunidade e clico na aba "Configuração de fases", nenhum conteúdo aparece.
**Recomendação:** O conteúdo das fases de avaliação deve aparecer.

Como está aparecendo:

![Image](https://github.com/RedeMapas/mapas/assets/95487110/3f4f8392-c2d3-4e96-9998-f601f36ee101)

**Comment by vicmagpac** [comment]
Task atualizada, aguardando reviewer no PR: https://github.com/RedeMapas/mapas/pull/207
