### ISSUE TITLE
[FRAMEWORK] Avaliador | Inscrição em edital | Prototipar notificações de atualizações das etapas de avaliação (task 9)

### ISSUE THREAD

**Issue by fabianecst** [RedeMapas/mapas#173]
**Escopo**
Proporcionar notificações ao avaliador sobre projetos liberados para avaliação e sua respectiva fase de avaliação atual para melhor controle e identificação de projetos com fases prontas para análise.  

- [ ] Prototipar telas que atendam o fluxo de notificações de projetos prontos para avaliar
- [ ] Validar telas internamente (design)
- [ ] Validar telas MinC e Uirá

**Comment by RaniGub** [comment]
O time de design está realizando uma curadoria de issues... entendemos que as novas trarão o escopo das anteriores quando for oportuno.
