### ISSUE TITLE
[FRAMEWORK] Avaliador | Inscrição em edital | Feature de FAQ (task 10)

### ISSUE THREAD

**Issue by fabianecst** [RedeMapas/mapas#176]
**Escopo**
Para atender a priorização verificada no fluxo de jornadas sobre o fortalecimento do canal de comunicação e FAQ para orientar sobre documentação, será necessário revisar e, se necessário, prototipar a feature de FAQ para que melhor atenda essa dor.

- [ ] Revisar a feature de FAQ em relação ao auxilio do envio de documentação por inscritos
- [ ] Prototipar telas que atendam o fluxo
- [ ] Validar telas internamente (design)
- [ ] Validar telas MinC e Uirá

**Comment by RaniGub** [comment]
O time de design está realizando uma curadoria de issues... entendemos que as novas trarão o escopo das anteriores quando for oportuno.
