### ISSUE TITLE
[FRAMEWORK] Avaliador | Inscrição em edital | Análise de recursos (task 18)

### ISSUE THREAD

**Issue by fabianecst** [RedeMapas/mapas#182]
**Escopo**
Atualmente, o recebimento de recursos é feito por e-mail e, em busca de trazer todo o fluxo do avaliador para o Mapas, é necessário prototipar a análise dos recursos em tela.

- [ ] Mapear a análise de recursos atual
- [ ] Prototipar telas que atendam o fluxo
- [ ] Validar telas internamente (design)
- [ ] Validar telas MinC e Uirá

**Informações complementares**

**Comment by RaniGub** [comment]
O time de design está realizando uma curadoria de issues... entendemos que as novas trarão o escopo das anteriores quando for oportuno.
