### ISSUE TITLE
[FRAMEWORK] Gestor Cultural | Elaboração Edital Preliminar | Prototipar tela com resumo do Edital (task 1)

### ISSUE THREAD

**Issue by drabelodesign** [RedeMapas/mapas#184]
**Escopo:** propor melhorias e nova organização para tela de exibição das oportunidades.
- [ ] Mapear as informações que serão apresentadas aos usuários como resumo da oportunidade
- [ ] Mapear documentos normalmente anexados à oportunidade
- [ ] Validação (Design)
- [ ] Validação (Minc. e Uirá)

**Comment by RaniGub** [comment]
O time de design está realizando uma curadoria de issues... entendemos que as novas trarão o escopo das anteriores quando for oportuno.
