### ISSUE TITLE
[FRAMEWORK] Gestor Cultural | Elaboração Edital Preliminar | Prototipar tela de criação de edital (task 3)

### ISSUE THREAD

**Issue by drabelodesign** [RedeMapas/mapas#185]
**Escopo:** necessidade de criar um espaço onde o Gestor possa acessar modelos de editais, facilitando com isso a criação de oportunidades.
- [ ] Prototipação da tela de formulário de criação do edital preliminar
- [ ] Prototipação de tela de edital publicado com informações de resumo
- [ ] Validação (Design)
- [ ] Validação (Minc. e Uirá)

**Comment by RaniGub** [comment]
O time de design está realizando uma curadoria de issues... entendemos que as novas trarão o escopo das anteriores quando for oportuno.
