### ISSUE TITLE
[FRAMEWORK] Gestor Cultural | Elaboração Edital Preliminar | Prototipar tela de dicionário jurídico (task 27)

### ISSUE THREAD

**Issue by drabelodesign** [RedeMapas/mapas#187]
**Escopo:** Criação de espaço na plataforma que ajude o Gestor com linguagem acessível a consultar e a compreender termos/linguagens jurídicas dos termos e das minutas das leis.
- [ ] Mapear quais informações deverão compor o Dicionário Jurídico
- [ ] Classificar as informações
- [ ] Prototipar tela de visualização do dicionário
- [ ] Validação (Design)
- [ ] Validação (Minc. e Uirá)

**Comment by RaniGub** [comment]
O time de design está realizando uma curadoria de issues... entendemos que as novas trarão o escopo das anteriores quando for oportuno.
