### ISSUE TITLE
[FRAMEWORK] Gestor Cultural | Elaboração Edital Oficial | Prototipar tela adicionar FAQ (task 2)

### ISSUE THREAD

**Issue by drabelodesign** [RedeMapas/mapas#188]
## *Objetivo*
Eu Como gestor cultural
Quero criar alimentar o FAQ da plataforma Mapas
Para reduzir o volume de perguntas repetitivas recebidas dos agentes, otimizando assim o meu tempo e o da minha equipe para responder a essas dúvidas.

## *Contexto*
Essa é uma etapa muito crítica, com processos manuais. O gestor já está extremamente sobrecarregado e ainda precisa dispensar seu tempo e da sua equipe respondendo as dúvidas dos agentes, quase sempre repetidas, por e-mail.

**Escopo:** Criar ferramenta que possibilite o Gestor criar um FAQ e incluir as respostar para dúvidas frequentes.
- [ ] Mapear principais perguntas e cruzar com informações do formulário do edital
- [ ] Prototipar tela com recursos para inclusão de FAQs
- [ ] Validação (Design)
- [ ] Validação (Minc. e Uirá)

## *Critérios de Aceitação*
Dado que o gestor precisa lidar com uma quantidade enorme de perguntas e que precisa respondê-las em um curto período de tempo e ainda lidar com muitas outras questões administrativas, quando centralizamos o processo de perguntas e respostas em uma única plataforma, criamos um FAQ com as principais dúvidas e disponibilizamos essas informações para todos os agentes e interessados, então o gestor consegue ter controle, classificar e otimizar o seu tempo.
Então resulta em alguma coisa

## *Observações*
[Links de apoio e informações adicionais] (https://www.figma.com/design/HkR1qdfHPn4riffcBBOQwR/Prot%C3%B3tipos-%7C-Prioriza%C3%A7%C3%B5es?node-id=562-7880&t=WHjZOpumhihT7tm8-4)

**Comment by RaniGub** [comment]
O time de design está realizando uma curadoria de issues... entendemos que as novas trarão o escopo das anteriores quando for oportuno.
