### ISSUE TITLE
[FRAMEWORK] Agente Cultural | Inscrição em edital | Selos de cotas (task 13)

### ISSUE THREAD

**Issue by emillecatarine** [RedeMapas/mapas#194]
**Escopo:** 

Atualmente, no Mapas, já existe a funcionalidade de Selos que indica, entre outras informações, se um usuário já tem alguma aprovação para participar de determinada categoria de cotas. Precisamos mapear quais são os selos que atendem às políticas afirmativas e como serão vinculados como comprovação válida caso um agente cultural decida se inscrever em uma oportunidade concorrendo às vagas de uma específica categoria de cotas.

**Tarefas:** 
- [ ]  Revisar os  selos de indicação de  enquandramento em  política afirmativa
- [ ]  Vincular selos à inscrição da oportunidade (políticas afirmativas)
- [ ]  Criar protótipos
- [ ]  Validar telas internamente (design)
- [ ]  Validar telas com MinC e Uirá

⚠️ Essa issue se relaciona com a issue #177 da jornada do avaliador cultural.

**Comment by RaniGub** [comment]
O time de design está realizando uma curadoria de issues... entendemos que as novas trarão o escopo das anteriores quando for oportuno.
