### ISSUE TITLE
[FRAMEWORK] Agente Cultural | Inscrição em edital | Políticas afirmativas (task 14 15 20)

### ISSUE THREAD

**Issue by emillecatarine** [RedeMapas/mapas#195]
**Escopo:** 

Atualmente, no Mapas, um agente pode concorrer à uma vaga por cotas apenas afirmando que se enquadra na categoria em questão. Pretendemos melhorar esse processo adicionando a possibilidade de três tipos de confirmação: 1) selos (issue #194); 2) comprovação documental de enquadramento na categoria pretendida; 3) agendamento de bancas de heteroidentificação.

**Tarefas:** 
- [ ]  Mapear fluxo de validação  de documentos anexados pelo inscrito  referentes a comprovação da política  afirmativa (task 14)
- [ ]  Definir critérios  de aceitação para que não seja  necessária uma banca de  validação (task 20)
- [ ]  Prototipar fluxo de políticas afirmativas (com aprovação e parecer do gestor e/ou avaliador cultural)
- [ ]  Validar telas internamente (design)
- [ ]  Validar telas com MinC e Uirá

⚠️ Essa issue se relaciona com as issues #179 e #180 da jornada do avaliador cultural.

**Comment by RaniGub** [comment]
O time de design está realizando uma curadoria de issues... entendemos que as novas trarão o escopo das anteriores quando for oportuno.
