### ISSUE TITLE
[FRAMEWORK] Agente Cultural | Inscrição em edital | FAQ (task 2)

### ISSUE THREAD

**Issue by emillecatarine** [RedeMapas/mapas#198]
**Escopo:** 

Um dos apontamentos do MinC é que muitas das perguntas que os gestores culturais recebem são repetitivas e até mesmo simples de serem respondidas (as respostas já podem ser encontradas no próprio edital). A criação de um FAQ facilitaria ao agente cultural encontrar respostas às suas dúvidas sem ter que submeter ao gestor cultural e aguardar o período de resposta. Além disso, diminuiria a quantidade de demandas do gestor cultural, uma vez que o fluxo de perguntas possivelmente diminuiria.

**Tarefas:** 
- [ ]  Verificar se FAQ terá perguntas/respostas padrões para todas as oportunidades
- [ ]  Se sim, mapear perguntas/respostas padrões
- [ ]  Pensar em como/quando o gestor cultural poderá inserir novas perguntas/respostas no FAQ (sugestão: na criação da oportunidade, durante o período de inscrição, nos períodos de recurso)
- [ ]  Prototipar telas
- [ ]  Validar telas internamente (design)
- [ ]  Validar telas com MinC e Uirá

⚠️ Essa issue se relaciona com a issue #188 do fluxo do gestor cultural.

**Comment by RaniGub** [comment]
O time de design está realizando uma curadoria de issues... entendemos que as novas trarão o escopo das anteriores quando for oportuno.
