### ISSUE TITLE
[FRAMEWORK] Agente Cultural | Inscrição em edital | Currículo do avaliador (task 21)

### ISSUE THREAD

**Issue by emillecatarine** [RedeMapas/mapas#199]
**Escopo:** 

Uma das solicitações do MinC foi que o agente cultural tenha mais transparência no seu processo de avaliação, inclusive tendo ciência de quem é seu avaliador e qual é o seu currículo.

**Tarefas:**
- [ ]  Mapear dados de  currículo de avaliador a serem  apresentados ao agente cultural
- [ ]  Prototipar tela
- [ ]  Validar telas internamente (design)
- [ ]  Validar telas com MinC e Uirá

⚠️ Essa issue se relaciona com a issue #166 do fluxo do avaliador cultural.

**Comment by RaniGub** [comment]
O time de design está realizando uma curadoria de issues... entendemos que as novas trarão o escopo das anteriores quando for oportuno.
