### ISSUE TITLE
[FRAMEWORK] Agente Cultural | Inscrição em edital | Recurso (task 22 23)

### ISSUE THREAD

**Issue by emillecatarine** [RedeMapas/mapas#200]
**Escopo:** 

A experiência de solicitação de recurso, atualmente, carece de muita nitidez. Não é fácil encontrar onde deve ser feita a solicitação, não há acompanhamento do andamento e não existe a possibilidade de solicitação de um parecer. Esse processo falta com transparência para o agente cultural e dificulta a comunicação com o gestor cultural.

**Tarefas:**
- [ ]  Prototipar solicitação de parecer (do  resultado da inscrição)  – é enviado pelo avaliador ou pelo gestor cultural?
- [ ]  Mapear e prototipar infos necessárias para solicitação do recurso
- [ ]  Mapear e prototipar o modelo de recurso 
- [ ]  Prototipar envio de recurso 
- [ ]  Prototipar acompanhamento do recurso
- [ ]  Prototipar resultado do recurso
- [ ]  Validar telas internamente (design)
- [ ]  Validar telas com MinC e Uirá

⚠️ Essa issue se relaciona com a issue #191 do fluxo do gestor cultural e #181 e #182 do fluxo do avaliador cultural.

**Comment by RaniGub** [comment]
O time de design está realizando uma curadoria de issues... entendemos que as novas trarão o escopo das anteriores quando for oportuno.
