### ISSUE TITLE
[FRAMEWORK] Agente Cultural | Inscrição em edital | Integração com gov.br (task 26)

### ISSUE THREAD

**Issue by emillecatarine** [RedeMapas/mapas#201]
**Escopo:** 

Algumas documentações solicitadas para a inscrição em edital podem já estar disponíveis no gov.br. A integração Mapas x Gov.br busca, então, facilitar o upload dessa documentação e trazer a segurança ao avaliador / gestor cultural de que a documentação já foi validada pelo próprio Governo Federal.

**Tarefas:**
- [ ]  Verificar possibilidade de integração Mapas x Gov.br
- [ ]  Prototipar telas
- [ ]  Validar telas internamente (design)
- [ ]  Validar telas com MinC e Uirá

**Comment by RaniGub** [comment]
O time de design está realizando uma curadoria de issues... entendemos que as novas trarão o escopo das anteriores quando for oportuno.
