### ISSUE TITLE
[OPORTUNIDADE] Não há opções para critérios de desempate

### ISSUE THREAD

**Issue by emillecatarine** [RedeMapas/mapas#206]
**Ocorrência:** desktop e mobile
**Contexto:** Em [oportunidades > gerenciar oportunidade > configuração de fases > adicionar fase de avaliação > avaliação técnica > configuração da avaliação > configuração de critérios de desempate] (print abaixo), o dropdown de seleção de critérios de desempate não apresenta nenhuma opção
**Recomendação:** É necessário apresentar a lista de critérios de desempate (verificar se existe essa lista no banco de dados. Se não houver, avisar para que eu tente coletar essas informações)

![Image](https://github.com/orgs/LabCDBr/projects/1/assets/95487110/ed829408-d79e-4a32-947a-e8f685f2425c)

**Comment by vicmagpac** [comment]
@emillecatarine realizamos o teste na oportunidade 181, realizamos a configuração na fase técnica em (configurações da avaliação) e no critério um apresenta dois critérios:

- Média de uma seção de critérios de avaliação
- Nota de um critério de avaliação

![image](https://github.com/RedeMapas/mapas/assets/3487411/b495f658-5c9a-4cad-8cca-80db436dbd91)

Qual o id da oportunidade que você verificou?

**Comment by lpirola** [comment]
@emillecatarine se tiver mais problemas, pode reabrir
