### ISSUE TITLE
[ÉPICO] Tela de configurações Mapas

### ISSUE THREAD

**Issue by RaniGub** [RedeMapas/mapas#208]
**Escopo**
Precisamos disponibilizar algumas opções que tornem possível a configuração de algumas opções na plataforma Mapas.

## **Configurações gerais**

- [x] #276

## **Configurações de termos/taxonomias**
- [x] #277

## **Configurações de entidades/termo/filtro**
- [x] #278

## **Configurações de tema/imagem/cores**
- [x] #279

## **Configurações de documentos**
- [x] #412 

# **Escopo DEV** 

## **Definição de arquitetura**

- [ ] #415

## **Configurações gerais**

- [ ] #416

## **Configurações de documentos**

**Informações complementares**
[Ambiente de homologação para explorar o cenário atual](https://mapaculturalhomolog.secult.ce.gov.br/) Entrar no meu Meus Subsites no Painel de Controle

![Image](https://github.com/RedeMapas/mapas/assets/79097920/b87b3ca4-7bc7-49d9-a7b5-c1806afb3ee5)

![Image](https://github.com/RedeMapas/mapas/assets/79097920/16027f84-d42c-426f-9143-d5e72bdd7d3e)

**Comment by juscoton** [comment]
Discovery iniciado dia 16/07, em agenda com Uirá e Lucas, onde foram discutidos os seguintes pontos:
- Foi feito o acesso em conjunto à Plataforma Mapas Seculte CE e discussão da estrutura de configurações apresentada lá.
- Repasse das telas produzidas pelo HackLab e entender o que poderá ser aproveitado.
- Foi feito um primeiro esboço da estrutura que iremos propor.

**Comment by RaniGub** [comment]
Épico finalizado.
