### ISSUE TITLE
Criar painel de dados no Metabase - Agentes

### ISSUE THREAD

**Issue by wforte88** [RedeMapas/mapas#215]
## **Contexto**

- Realizar implementação de dashboard da entidade de agentes, onde seja possível acompanhar indicadores em tempo real para tomada de decisão por parte da equipe de gestão do mapas.

## **Escopo UX**

- Não se aplica

## **Escopo DEV**

- [x] Criar indicador de quantidade de agentes
- [x] Criar indicador de agentes por gênero
- [x] Criar indicador de agente por raça
- [x] Criar indicador de agente por distribuição por município
- [x] Criar indicador de agentes cadastrados por períodos
- [ ] Criar indicador de agente por área de atuação
- [ ] Criar indicador de agente por idade
- [ ] Criar indicador de agente por escolaridade
- [ ] Criar indicador de agente por comunidade

## **Critérios de Aceitação**

- [ ] Acesso a dashboard de agentes  
**Dado que** sou um usuário do metabase  
**Quando** acesso a ferramenta do metabase
**então** visualizo o dashboard de agentes

# Observações

A task se refere a implementação especificamente do dashboard de agentes.

**Comment by lpirola** [comment]
@wforte88 queria dar essa tarefa para Kauane mas ela não tá aqui na organização. Pelo que eu vi, nem a Anne.

Essa tarefa pode ser feita por ela, só com a supervisão do Elliot ou do Cajazeiras, ambos também não estão por aqui ainda.
