### ISSUE TITLE
Configuração do RedeMapas nos servidores do MinC

### ISSUE THREAD

**Issue by lpirola** [RedeMapas/mapas#219]
### Escopo
Instalar e configurar o Mapas com o banco de dados migrado no ambiente de testes

### Objetivo
Realizar o showcase com com o painel de dados funcionando com os dados migrados pela equipe da STII

### Etapas

- [x] Conseguir acesso a VPN e Kubernetes
- [x] Criar configuração Kubernetes para v7
- [x] Instalação da configuração no cluster Kubernetes do Ministério
- [ ] Correção dos bugs nesse ambiente, relacionado a ferramenta de upload

**Comment by wforte88** [comment]
@lpirola @vicmagpac verificar esta tarefa para especificá-la melhor. Quais são os bugs pendentes, quais são a estimativa?
