### ISSUE TITLE
Modelo de edital | Fomento à Execução de Ações Culturais

### ISSUE THREAD

**Issue by RaniGub** [RedeMapas/mapas#231]
## Objetivo
**Eu Como** Gestor Cultural  
**Quero** ter a opção de acessar um modelo de edital de Fomento à Execução de Ações Culturais
**Para** publicá-lo no padrão que atenda os requisitos da PNAB

## Contexto
- O MinC disponibilizou modelos de editais para que possamos criar as experiências para que o Gestor Cultural publique seus editais de forma padronizada, atendendo os critérios da PNAB.

## Escopo do Time de Design 
- [x] Analisar documento e compreender os campos necessários no formulário do Mapas
- [ ] Prototipar interface do modelo: Fomento à execução de ações culturais
- [ ] Aprovação Uirá
- [ ] Aprovação Design
 
## Critérios de Aceitação
**Dado que** uma pessoa gestora necessita publicar um edital de Fomento à Execução de Ações Culturais da PNAB
**Quando** ela acesse a tela de criação de oportunidades/editais
**Então** ela consegue selecionar a opção de modelo desejado

## Observações
[Documentos de referência](https://drive.google.com/drive/folders/1813P7LrA-ttr38OrT6Rm5ecc7gVyWjBX?usp=sharing)
[Figma](https://www.figma.com/design/HkR1qdfHPn4riffcBBOQwR/Prot%C3%B3tipos-%7C-Prioriza%C3%A7%C3%B5es?node-id=586-6666&t=0DKBbj9jVs1BpQNq-4)

**Comment by drabelodesign** [comment]
Link do Protótipo:
https://www.figma.com/design/HkR1qdfHPn4riffcBBOQwR/Prot%C3%B3tipos-%7C-Prioriza%C3%A7%C3%B5es?node-id=586-6666&t=0DKBbj9jVs1BpQNq-4

**Comment by RaniGub** [comment]
Tarefa finalizada. Foi optado o caminho de criação de modelos de editais pelas configurações de oportunidades.
