### ISSUE TITLE
Implementar listagem de selos (válidos, pendentes, expirados e excluídos)

### ISSUE THREAD

**Issue by wforte88** [RedeMapas/mapas#246]
## **Objetivo**

Eu Como agente cultural  
Quero visualizar a listagem dos meus selos por situações (Válidos, pendentes, expirados e excluídos)
Para que outras pessoas do Mapas possam ver, e/ou para que possam ser utilizados como validação para determinadas especificidades do fluxo de inscrição em edital (por exemplo: cotas, avaliador)

## **Contexto**

O sistema deve permitir ai gerenciar o perfil do agente, deve aparecer uma nova aba com o gerenciamento "Meus selos".

## **Critérios de Aceitação**

- [ ] Lista de selos por situação
**Dado que** acesso o perfil de edição do agente
**Quando** clico na nova aba "Meus selos"
**então** deve aparecer a lista dos selos com as situações separados por abas

## Atividades

- [x] Criação das abas 
- [x] Carregar os selos pela API
- [x] Separar selos como válidos e expirados
- [ ] Melhorar interface proposta

## **Observações**

[Link do figma](https://www.figma.com/design/HkR1qdfHPn4riffcBBOQwR/Prot%C3%B3tipos-%7C-Prioriza%C3%A7%C3%B5es?node-id=392-3522&t=8vS5ktgaAiJxRhUl-4)

**Comment by lpirola** [comment]
Nessa primeira versão, apenas a aba válidos e expirados serão implementadas pois os outros status precisão das ações implementadas para aparecer na listagem.

De toda forma, deixei comentado as outras abas para implementar quando estiver pronta a funcionalidade de excluir e de aceitar os selos.

**Comment by lpirola** [comment]
@wforte88 @vicmagpac  existe um refinamento de UI nas abas e na página que não estão presentes atualmente na interface da aplicação e que eu não estava contemplando. Algumas mudanças que fiz causaram impacto em outras páginas, é importante alinhar o quanto vamos fazer modificações no design system para mensurar corretamente.

@emillecatarine @RaniGub  esse refinamento existe mesmo ou podemos seguir sem ele do ponto de vista de Design? É um requisito obrigatório para essa atividade estar concluída?

**Comment by lpirola** [comment]
Outro problema, é que ao adotar a estratégia de ter uma aba dentro de outra aba, a navegação padrão do componente fica quebrada, no caso da pessoa regarregar a página dentro da aba de selos válidos ela é redirecionada para primeira aba.

**Comment by LeonardoZanotti** [comment]
Atualização:

![Image](https://github.com/user-attachments/assets/753d0389-5baf-47ed-a269-8308de79edde)

Fiz uma reunião com o Victor que me esclareceu muitas dúvidas.
Já foi implementado a aba de selos na edição do agente e já estou conseguindo receber os dados da API.

Vou trabalhar agora em dar o estilo conforme o figma.

**Comment by LeonardoZanotti** [comment]
Atualização:

![image](https://github.com/user-attachments/assets/372c4013-5a37-48e5-8078-f8286b4455b8)

Adicionei uma requisição no arquivo `apiQuery.php` para pegar todas as informações do sealRelation e inclui esses dados dentro do retorno, então agora já estamos recebendo todos os dados do API no front. Vou finalizar a formatação e estilização desses dados.

**Comment by LeonardoZanotti** [comment]
Atualização:
![image](https://github.com/user-attachments/assets/337b28de-d53f-4dc5-a878-2fa214474e4e)
Todas as informações dos selos estão sendo mostradas na tela e já estão separados em válidos e expirados.
Preciso trabalhar ainda na estilização e em adicionar os botões de exclusão do selo e checkbox de mostrar no perfil.

**Comment by lpirola** [comment]
@papatrock vai dar uma ajuda com css. @LeonardoZanotti em qual branch vc está trabalhando?

**Comment by LeonardoZanotti** [comment]
> @papatrock vai dar uma ajuda com css. @LeonardoZanotti em qual branch vc está trabalhando?

a branch é a 246-implementar-listagem-de-selos-vlidos-pendentes-expirados-e-excludos

**Comment by papatrock** [comment]
Atualização: fiz algumas estilizações básicas, ainda falta ajustar o tamanho e cores


![Image](https://github.com/user-attachments/assets/832df325-b540-481e-89e0-595e9f8720e1)

**Comment by papatrock** [comment]
Coloquei as cores corretas, falta só ajustar o tamanho das divs e o botão


![Image](https://github.com/user-attachments/assets/d1b4ec3e-d4f7-4079-9765-a57cfc006237)

**Comment by LeonardoZanotti** [comment]
Exclusão de selos funcionando, após confirmar a exclusão a página é recarregada.

![Image](https://github.com/user-attachments/assets/cd7d6a27-2a8b-45dc-b7a7-f1b4bb36dda8)
