### ISSUE TITLE
[ÉPICO] Login Gov.br 

### ISSUE THREAD

**Issue by juscoton** [RedeMapas/mapas#264]
## *Objetivo*
A página de Login Gov.br consiste na página de acesso à Plataforma Mapas com integração à Plataforma Gov.br, para agregar segurança e autenticidade, também na tela de Configurações Gerais do Mapas, onde será possível: editar as configurações do usuário; configurar termos e taxonomias; configurar entidades, termos e filtros; configurar temas, imagens e cores.

## *Telas*
- [ ] #265 

## *Observações*
Links da estruturação desse fluxo no Roadmap:
https://www.figma.com/board/181VOj4DVixEuGyKjfQeXT/RoadMap%2C-Fluxo-de-Fomento-e-Banco-de-Problemas?node-id=1508-9211&t=0CosJxFN7O04cJ2h-1

**Comment by RaniGub** [comment]
@juscoton após o momento de discovery, avalie se faz sentido essa tarefa se configurar como sendo um Épico. Senão, deixe somente a #265 criada.

**Comment by RaniGub** [comment]
As tarefas do Login-gov.br não se configuraram como um Épico, mas como uma tarefa com menor esforço. Logo será finalizado.
