### ISSUE TITLE
Alterar o logo da Rede Mapas

### ISSUE THREAD

**Issue by RaniGub** [RedeMapas/mapas#284]
## *Contexto*
Nos protótipos, está sendo utilizado o logo do Mapas Culturais ao invés da Rede Mapas. Considerando a generalidade da plataforma, é preciso fazer essa atualização.

## *Escopo do Time*
- [x] Atualizar nos protótipo o logo da Rede Mapas

## *Critérios de Aceitação*
Dado que uma pessoa acesse os protótipos
Quando ela abre qualquer página
Então ele consegue visualizar o logo da Rede Mapas

## *Observações*
https://www.figma.com/design/HkR1qdfHPn4riffcBBOQwR/Prot%C3%B3tipos-%7C-Prioriza%C3%A7%C3%B5es?node-id=1227-11670&t=5arYidhH1K5TMAcI-4

**Comment by RaniGub** [comment]
Oi @juscoton @emillecatarine por gentileza, aplicar essa alteração nas telas já feitas e em andamento.

**Comment by emillecatarine** [comment]
Atualização finalizada nas telas que vão seguir para desenvolvimento.
