### ISSUE TITLE
Desacoplar campo "Pessoa com deficiência" para campos separados (outros)

### ISSUE THREAD

**Issue by vicmagpac** [RedeMapas/mapas#308]
## *Objetivo*

Eu Como agente cultural  
Quero realizar a atualização do meu perfil e especificar que sou uma pessoa com deficiência
Para permitir especificar se tenho deficiência e qual tipo

## *Contexto*

Atualmente no mapa existe  campo "Pessoa com deficiÊncia", o campo trata a regra com "Não sou", "Visual", "Mental", "Física", "Auditiva". A solicitação é desacoplar esse campo e criar dois, o primeiro deve ser Pessoa com deficiÊncia (Sim ou não), se marcado sim deve aparecer outro campo para o agente especificar  quais deficiências o mesmo tem.

## **Critérios de Aceitação**

- [ ]  Permitir especificar se agente tem deficiência
**Dado que** acesso a página de edição do agente
**Quando** visualizo o campo de "Pessoa com deficiência"
**então** deve aparecer a opção sim ou não

- [ ]  Permitir especificar quais deficiências o agente tem caso marcado sim no critério acima
**Dado que** acesso a página de edição do agente
**Quando** especifico que tenho deficiência
**então** deve aparecer outro campo mostrando as opções de quais deficiências o agente tem

## *Observações*

[Link do figma]([https://www.figma.com/design/HkR1qdfHPn4riffcBBOQwR/Protótipos-|-Priorizações?node-id=187-7175&t=8yZcaz2kIlg2EClg-11](https://www.figma.com/design/HkR1qdfHPn4riffcBBOQwR/Prot%C3%B3tipos-%7C-Prioriza%C3%A7%C3%B5es?node-id=187-7175&t=8yZcaz2kIlg2EClg-11))

**Comment by lpirola** [comment]
Não será implementado devido a entendimento de que não será separado. 

@RaniGub esse acordo está refletido nas telas?

**Comment by RaniGub** [comment]
> Não será implementado devido a entendimento de que não será separado.
> 
> @RaniGub esse acordo está refletido nas telas?

@lpirola bati um papo com a @emillecatarine e foi compreendido que a opção que será seguida não reflete o protótipo, pois esse acordo foi dado "fora" das especificações iniciais. Acredito que entre o Uirá e time de tecnologias.
