### ISSUE TITLE
Implementação novo layout edição do agente

### ISSUE THREAD

**Issue by vicmagpac** [RedeMapas/mapas#309]
## *Objetivo*
Eu Como agente cultural  
Quero adicionar/editar as informações do meu perfil 
Para que outras pessoas do Mapas possam ver, e/ou para que as informações possam ser utilizadas na minha inscrição em oportunidades

## *Contexto*
Existe a necessidade de um cadastro de agente cultural individual que colete as informações básicas necessárias para a experiência na plataforma Mapas. É preciso mapear quais são essas necessidades básicas e prototipar a maneira como serão coletadas. A implementação específica dessa atividade é a remodelagem dos componentes de edição do agente.

## *Observações*
[Link do figma](https://www.figma.com/design/HkR1qdfHPn4riffcBBOQwR/Prot%C3%B3tipos-%7C-Prioriza%C3%A7%C3%B5es?node-id=200-2929&t=JOksIZ9PIJyUSXfb-4)

**Comment by vicmagpac** [comment]
A atividade está sendo gerenciada na branch: https://github.com/RedeMapas/mapas/tree/feature/atualiza-componentes-agentes-edicao

**Comment by lpirola** [comment]
https://github.com/RedeMapas/mapas/pull/301

**Comment by PaG0Dezaum2005** [comment]
### Vou dividir essa tarefa em outras tarefas menores:

**1. Criar as checkboxes de "Mostrar no perfil" para cada campo, exemplo:**
![Screenshot from 2024-08-06 09-53-50](https://github.com/user-attachments/assets/8e270df1-9802-4bab-b273-d756b5a08585)

**2. Criar tool tip "?" com mais informações nos campos desejados, exemplo:**
![Screenshot from 2024-08-05 18-44-39](https://github.com/user-attachments/assets/f568ba7e-286a-49e3-949a-f95416c8bf31)

**3. Criar botões para adicionar mais campos, como endereço alternativo, outros dados bancários, exemplo:** 
![Screenshot from 2024-08-06 10-08-15](https://github.com/user-attachments/assets/e542d6d8-687c-4e0b-aebb-c52f818ffb7c)
![Screenshot from 2024-08-06 10-08-41](https://github.com/user-attachments/assets/0976874d-dfe4-4953-901d-08badd154de2)

4.  Otimizar layout da página, com mais interatividade, espaçamento correto, cores corretas, de acordo com o figma.

@lpirola

**Comment by lpirola** [comment]
@PaG0Dezaum2005 segue as respostas:

1. não deve ser priorizado pois é uma funcionalidade que não existe ainda e estamos focados apenas em ajustes de ux/ui, deixando para outro momento essa nova funcionalidade.
2. ok
3. seguindo a recomendação de ajustes apenas ux/ui, não implementaremos a possibilidade de adicionar mais de um endereço e conta bancária.
4. ok

**Comment by PaG0Dezaum2005** [comment]
Atual situação da página @emillecatarine @lpirola 
![image](https://github.com/user-attachments/assets/c7dddc56-f2b6-4eac-bda7-3d49af809a1f)
![image](https://github.com/user-attachments/assets/a40ef946-3ec8-4820-942f-353d66cd811e)
![image](https://github.com/user-attachments/assets/3c626274-ca50-4fff-9283-df657d3c198a)
![image](https://github.com/user-attachments/assets/651ddb41-de95-4462-a26c-d775198889a4)
![image](https://github.com/user-attachments/assets/4b4fd68e-5c26-4831-8098-b359d18966c6)
