### ISSUE TITLE
Desacoplar campo "Comunidades tradicionais" para campos separados (outros)

### ISSUE THREAD

**Issue by vicmagpac** [RedeMapas/mapas#310]
## *Objetivo*

Eu Como agente cultural  
Quero realizar a atualização do meu perfil e especificar o dado "Comunidade tradicionais"
Para permitir especificar as comunidades

## *Contexto*

Atualmente no mapa existe  campo "Comunidade tradicionais", o campo trata a regra com "Não pertenço", "COmunidade 1", "COmunidade 2" e etc. A solicitação é desacoplar esse campo e criar dois, o primeiro deve ser Pertence a comunidade tradicional (Sim ou não), se marcado sim deve aparecer outro campo para o agente especificar  quais comunidades o mesmo participa.

## **Critérios de Aceitação**

- [ ]  Permitir especificar se agente participa de Comunidade tradicionais
**Dado que** acesso a página de edição do agente
**Quando** visualizo o campo de "Comunidade tradicionais"
**então** deve aparecer a opção sim ou não

- [ ]  Permitir especificar quais  Comunidade tradicionais o agente participa caso marcado sim no critério acima
**Dado que** acesso a página de edição do agente
**Quando** especifico que participo de comunidades
**então** deve aparecer outro campo mostrando as opções de quais Comunidade tradicionais o agente participa

## *Observações*

Link figma: https://www.figma.com/design/HkR1qdfHPn4riffcBBOQwR/Protótipos-|-Priorizações?node-id=187-7175&t=8yZcaz2kIlg2EClg-11](https://www.figma.com/design/HkR1qdfHPn4riffcBBOQwR/Prot%C3%B3tipos-%7C-Prioriza%C3%A7%C3%B5es?node-id=187-7175&t=8yZcaz2kIlg2EClg-11

**Comment by lpirola** [comment]
Não será implementado devido a entendimento de que não será separado.

@RaniGub esse acordo está refletido nas telas?
