### ISSUE TITLE
Adicionar a lista de meus modelos na lista de minhas oportunidades

### ISSUE THREAD

**Issue by vicmagpac** [RedeMapas/mapas#324]
## *Objetivo*

Eu Como agente cultural  logado na aplicação
Quero acessar a lista dos meus modelos de oportunidades
Para gerenciar os meus modelos

## *Contexto*

Implementação do gerenciamento de modelos de oportunidades.

## **Critérios de Aceitação**

- [ ] Lista de meus modelos de oportunidades
**Dado que** acesso minhas oportunidades
**Quando** acesso a aba de "Meus modelos"
**então** deve aparecer a lista dos meus modelos de acordo com o figma abaixo

## *Observações*

Link figma: https://www.figma.com/design/HkR1qdfHPn4riffcBBOQwR/Prot%C3%B3tipos-%7C-Prioriza%C3%A7%C3%B5es?node-id=1755-15271&t=HGItppDBQMhj7dV0-0

**Comment by PaG0Dezaum2005** [comment]
@LeonardoZanotti @fns21 , já começamos essa task na branch feature/meus-modelos-dados-e-estilizacao. 
Temos duas coisas principais para terminar:
1. Estilização da página, a maior parte ja está feita, faltam apenas pequenos ajustes.
2. Puxar informações sobre os modelos do backend para ficar de acordo com o figma. Ainda estamos tentanto entender de onde temos que puxar esses dados, entao é bom todos nós focarmos nisso.

**Comment by papatrock** [comment]
### Atualização:
criei um novo endpoint que retorna os dados do bd pedidos no figma, a rota é:
`/api/findOpportunitiesModels`


![Image](https://github.com/user-attachments/assets/48c15436-a3b4-42fa-8bd9-173843136fa5)
