### ISSUE TITLE
Sistematização das Informações | Configuração de oportunidade

### ISSUE THREAD

**Issue by drabelodesign** [RedeMapas/mapas#334]
## **Contexto**
O processo de configuração das fases de uma oportunidade necessita de um redesenho completo. Atualmente, a interface e os recursos de configuração são confusos e pouco intuitivos. É essencial que esse ambiente seja redesenhado para se tornar mais acessível e intuitivo, além de estar preparado para receber modelos de edital compatíveis com as exigências da PNAB.

## **Escopo do Time**
- [x] Analisar a interface e os modelos de edital da PNAB
- [x] Mapear os recursos e os campos atuais e os exigidos no modelo 'Fomento à Execução de Ações Culturais'
- [x] Organizá-los em categorias

## **Critérios de Aceitação**
Dado que é necessário reconstruir o ambiente de configuração de oportunidades 
Quando preciso incorporar os novos modelos de edital da PNAB, 
Então é fundamental, ao prototipar as telas, entender onde e como as informações deverão ser alocadas e organizadas.

## **Observações**
Será indispensável realizar muitas conversas e alinhamentos de expectativas com o Uirá, pois várias funcionalidades estão confusas e é difícil identificar seu papel no fluxo de criação de oportunidades. Será necessário mapear todas as exigências de cada modelo de edital e compreender o que já está pré-definido nas telas de configuração. Somente após essa etapa poderemos iniciar a prototipagem.

[Figma](https://www.figma.com/design/HkR1qdfHPn4riffcBBOQwR/Prot%C3%B3tipos-%7C-Prioriza%C3%A7%C3%B5es?node-id=1755-44382&t=6cBySbIjMRjzX8q3-4)

**Comment by drabelodesign** [comment]
Finalizei a sistematização das informações, dentro do que consegui identificar no Mapas, nos modelos e nos anexos disponibilizados.
É provável que ao longo do caminho outros recursos e campos sejam encontrados.
Para que o fluxo não fique travado, vou trabalhando nos componentes do protótipo naquilo que sentir mais segurança.

**Comment by RaniGub** [comment]
Como compreendido em pareamento com o time de design, essa atividade dará subsídio para as demais com escopo de configuração de oportunidades. Dessa forma, podemos dar ela como encerrada, entendendo que eventualmente poderá ser atualizada nos pareamentos.
