### ISSUE TITLE
Requisitos da Oportunidade | Configuração de oportunidade

### ISSUE THREAD

**Issue by RaniGub** [RedeMapas/mapas#347]
## **Contexto**
Até o momento a configuração de oportunidades será dividia em quatro momentos. Os dois primeiros são para configurar o regulamento da oportunidade. A aba de 'Requisitos Gerais' faz parte o segundo momento e é onde o gestor configurará com mais detalhes quem poderá participar do processo de seleção, requisitos de avaliação, informações sobre cotas etc.

## **Escopo do Time**
- [ ] Analisar a interface, compreender os impactos que cada recurso refletirá em outros ambientes
- [ ] Prototipar interface
- [ ] Validar com Uirá
- [ ] Refinamento

## **Critérios de Aceitação**
Dado que o Gestor 
Quando está configurando as fases da oportunidade, precisa configurar o regulamento da oportunidade
Então seria pertinente disponibilizar um espaço próprio para isso que antecede à configuração de fases.

## **Observações**
Essa divisão foi pré-aprovada pelo Uirá, mas pode sofrer ajustes a medida que formos amadurecendo a ideia do protótipo.

[Figma](https://www.figma.com/design/HkR1qdfHPn4riffcBBOQwR/Prot%C3%B3tipos-%7C-Prioriza%C3%A7%C3%B5es?node-id=1760-23662&t=fEzOYNsCy8z8jyHc-4)

**Comment by RaniGub** [comment]
Infos de atualização do Danilo: Essa tarefa está planejada para ser finalizada na sprint 10, após a #346. É a segunda aba da tela de configuração de oportunidades.

**Comment by drabelodesign** [comment]
As funcionalidades que ocupariam essa aba foram migradas para a atividade Configuração de Formulário, conforme organizado nessa seção: 
[Figma](https://www.figma.com/design/HkR1qdfHPn4riffcBBOQwR/Prot%C3%B3tipos-%7C-Prioriza%C3%A7%C3%B5es?node-id=2050-30255&t=BWAM9tpggQ74saig-4)
