### ISSUE TITLE
Administradores da organização | Organizações (páginas públicas)

### ISSUE THREAD

**Issue by RaniGub** [RedeMapas/mapas#374]
## *Objetivo*
**Eu como** 
**Quero**
**Para**

## *Contexto*
- 

## *Escopo Design*

- [ ] Discovery
- [ ] Prototipar interface
- [ ] Validação
- [ ] Refinamento
- [ ] Validação Uirá/MinC

**Dado que**
**Quando**
**Então**

## *Observações*
Inserir o link do protótipo aqui

**Comment by emillecatarine** [comment]
Optamos por mostrar os administradores da organização na aba "Agentes relacionados", em uma sub-aba chamada [Administradores](https://www.figma.com/design/HkR1qdfHPn4riffcBBOQwR/Prot%C3%B3tipos-%7C-Prioriza%C3%A7%C3%B5es?node-id=2286-22805&t=7kzEDbNAqCYiFZuO-11). Essa issue, então, não será mais utilizada.
