### ISSUE TITLE
Projetos em execução/aprovados | Organizações (páginas públicas)

### ISSUE THREAD

**Issue by RaniGub** [RedeMapas/mapas#376]

**Comment by emillecatarine** [comment]
Não trataremos mais como projetos. Adaptamos para iniciativas, que serão exibidas no modo de edição (#408) e visualização (#409)

**Comment by emillecatarine** [comment]
Não trataremos mais como projetos. Adaptamos para iniciativas, que serão exibidas no modo de edição (https://github.com/RedeMapas/mapas/issues/408) e visualização (https://github.com/RedeMapas/mapas/issues/409)
