### ISSUE TITLE
Agentes relacionados | Iniciativas (páginas públicas)

### ISSUE THREAD

**Issue by RaniGub** [RedeMapas/mapas#389]
## *Objetivo*
**Eu como** 
**Quero**
**Para**

## *Contexto*
- 

## *Escopo Design*

- [ ] Discovery
- [ ] Prototipar interface
- [ ] Validação
- [ ] Refinamento
- [ ] Validação Uirá/MinC

**Dado que**
**Quando**
**Então**

## *Observações*
Inserir o link do protótipo aqui

**Comment by emillecatarine** [comment]
Agentes relacionados serão contemplados na aba "Pessoas": #386
