### ISSUE TITLE
[OPORTUNIDADE] Depois de publicada uma oportunidade, permanece o aviso de que está em rascunho

### ISSUE THREAD

**Issue by emillecatarine** [RedeMapas/mapas#42]
**Contexto:** Enquanto uma oportunidade está em rascunho, fica o aviso "Este oportunidade está em rascunho. Você Você precisa publicar para exibir para todas as pessoas" (print abaixo).  Quando eu publico essa oportunidade, porém, o aviso permanece, deixando a impressão de que a ação de publicar não foi efetiva.
**Ocorrência:** desktop e mobile.
**Recomendação:** Excluir o aviso quando a oportunidade for publicada.

<img width="1224" alt="image" src="https://github.com/LabCDBr/gestao/assets/95487110/2aa77a75-5a83-47ea-b023-27a3cfa4d6a7">

**Comment by lpirola** [comment]
@Aushiffer poderia trazer uma atualização de como está?

**Comment by Aushiffer** [comment]
> @Aushiffer poderia trazer uma atualização de como está?
Estou tentando achar a parte na src relacionada à issue. No caso, a parte ligada à edição de oportunidades.

**Comment by Aushiffer** [comment]
Quando se recarrega a página, o status da entidade é atualizado e o aviso desaparece. O problema da issue continua válido ao saber disso?
