### ISSUE TITLE
[OPORTUNIDADE] Não permitir o cadastro de uma oportunidade com inscrições já encerradas.

### ISSUE THREAD

**Issue by emillecatarine** [RedeMapas/mapas#47]
**Contexto:** Atualmente, é possível cadastrar uma oportunidade com período de inscrição em datas já passadas. Sendo assim, o usuário pode cadastrar uma oportunidade com o período de inscrição já fechado.
**Ocorrência:** desktop e mobile.
**Recomendação:** não permitir selecionar datas passadas como possível período de inscrição (início) e/ou publicação de resultado.

**Comment by LeonardoZanotti** [comment]
![image](https://github.com/RedeMapas/mapas/assets/61800222/b89b3129-4ea4-44a2-87ed-5eb20507380f)

Estou trabalhando nesta task há algum tempo e ainda não consegui testar a criação de uma oportunidade com inscrição já encerrada devido a um outro bug que me impede de prosseguir na criação de uma oportunidade.

Ainda desconheço a causa do bug, mas nada acontece após preencher as informações iniciais da oportunidade e clicar no botão de Criar.

**Comment by LeonardoZanotti** [comment]
![image](https://github.com/user-attachments/assets/52b523b5-b216-4cfc-84b2-cf2390848d2a)

Acabei de realizar a correção deste bug neste commit aqui: https://github.com/RedeMapas/mapas/commit/dbc9b1f9facdd19bd35bc7f6949b59034c9ceae8

Acredito que esteja certinho pelos testes que fiz.

**Comment by lpirola** [comment]
@LeonardoZanotti massa, só vale abrir outro PR pq foi para a outra organização, tem q ser no rede mapas!

**Comment by LeonardoZanotti** [comment]
> @LeonardoZanotti massa, só vale abrir outro PR pq foi para a outra organização, tem q ser no rede mapas!

Eiiiiitaa, não vi que tava indo pro mapas culturais.
Fechei aquela PR e abri uma nova agora pra develop do rede mapas.

**Comment by vicmagpac** [comment]
Atividade está em processo de avaliação de PR.

**Comment by LeonardoZanotti** [comment]
PR atualizado: FIX - não permitir cadastros de inscrições já encerradas #297
