### ISSUE TITLE
[ÉPICO] Módulo intermediário

### ISSUE THREAD

**Issue by drabelodesign** [RedeMapas/mapas#533]
## *Objetivo*
Eu como Gestor Cultural
Quero criar os relatórios da oportunidade e disponibilizar o plano de trabalho no formulário de inscrição, no momento de inscrição da oportunidade.
Para acompanhar o andamento das inscrições e a execução dos projetos.

## *Contexto*
Entendemos que foi importante interromper o fluxo ideal para que para o time conseguisse entregar o fluxo funcionando minimamente da etapa de Execução, que compreende as funcionalidades de configuração e monitoramento de relatório, plano de trabalho, prestação de contas e recurso. 

Essa atividade é uma adaptação da jornada utilizando as propostas do "fluxo ideal" utilizando a estrutura atual do Mapas.

## *Escopo de Design*

**Relatórios**
- [x] Gestor: fluxo de criação e acompanhamento dos relatórios [Link](https://www.figma.com/design/HkR1qdfHPn4riffcBBOQwR/Prot%C3%B3tipos-%7C-Prioriza%C3%A7%C3%B5es?node-id=6237-75220&t=BZseVh0kuMCWn0Au-4)
- [x] Fiscais: fluxo de fiscalização de relatórios [Link](https://www.figma.com/design/HkR1qdfHPn4riffcBBOQwR/Prot%C3%B3tipos-%7C-Prioriza%C3%A7%C3%B5es?node-id=6237-78985&t=BZseVh0kuMCWn0Au-4)
- [x] Agente: fluxo de preenchimento e acompanhamento dos relatórios [Link](https://www.figma.com/design/HkR1qdfHPn4riffcBBOQwR/Prot%C3%B3tipos-%7C-Prioriza%C3%A7%C3%B5es?node-id=6250-101219&t=BZseVh0kuMCWn0Au-4)
- [x] Validação Uirá
- [x] Ajustes
- [x] Validação MinC.
- [ ] Ajustes finais

**Plano de Trabalho**
- [x] Gestor: Configuração e acompanhamento do Plano de Trabalho [Link](https://www.figma.com/design/HkR1qdfHPn4riffcBBOQwR/Prot%C3%B3tipos-%7C-Prioriza%C3%A7%C3%B5es?node-id=6237-82098&t=BZseVh0kuMCWn0Au-4)
- [x] Agente: painel de preenchimento e acompanhamento do Plano de Trabalho [Link](https://www.figma.com/design/HkR1qdfHPn4riffcBBOQwR/Prot%C3%B3tipos-%7C-Prioriza%C3%A7%C3%B5es?node-id=6256-59137&t=BZseVh0kuMCWn0Au-4)
- [x] Validação Uirá
- [x] Ajustes
- [x] Validação MinC.
- [ ] Ajustes finais

**Prestação de Contas**
- [x] Gestor [Link](https://www.figma.com/design/HkR1qdfHPn4riffcBBOQwR/Prot%C3%B3tipos-%7C-Prioriza%C3%A7%C3%B5es?node-id=6590-16294&t=g6sqw8FoTrxy2Gy5-4)
- [x] Avaliador [Link](https://www.figma.com/design/HkR1qdfHPn4riffcBBOQwR/Prot%C3%B3tipos-%7C-Prioriza%C3%A7%C3%B5es?node-id=6590-17286&t=g6sqw8FoTrxy2Gy5-4)
- [x] Agente [Link](https://www.figma.com/design/HkR1qdfHPn4riffcBBOQwR/Prot%C3%B3tipos-%7C-Prioriza%C3%A7%C3%B5es?node-id=6590-22185&t=g6sqw8FoTrxy2Gy5-4)
- [x] Validação Uirá
- [x] Ajustes
- [x] Validação MinC.
- [x] Ajustes finais

**Recursos**
- [x] Gestor
- [x] Avaliador
- [x] Agente
- [x] Validação Uirá
- [x] Ajustes
- [x] Validação MinC.
- [ ] Ajustes finais

## *Critérios de Aceitação*
Dado que o Gestor Cultural precisa criar os relatórios da oportunidade e disponibilizar o plano de trabalho no formulário de inscrição,
Quando ele está configurando uma oportunidade
Então é importante que ele possa acompanhar o andamento das inscrições e a execução dos projetos.
 

## *Observações*
[Link do fluxo](https://www.figma.com/design/HkR1qdfHPn4riffcBBOQwR/Prot%C3%B3tipos-%7C-Prioriza%C3%A7%C3%B5es?node-id=6237-52115&node-type=canvas&t=EfOwa5cySvdXsxpK-0)

**Comment by drabelodesign** [comment]
Essa atividade foi desemembrada em 4 issues, que chamamos de Módulos Intermediários: 
1. Módulo Intermediário | Relatórios - #542 
2. Módulo Intermediário | Plano de Trabalho - #543 
3. Módulo Intermediário | Prestação de cintas - #544 
4. Módulo Intermediário | Recursos - #545 

Todas estão concluídas

**Comment by drabelodesign** [comment]
@RaniGub devo fechar essa issue?

**Comment by RaniGub** [comment]
Épico finalizado
