### ISSUE TITLE
Deixar os testes automatizados com phpunit passando

### ISSUE THREAD

**Issue by lpirola** [RedeMapas/mapas#54]

**Comment by LeonardoZanotti** [comment]
Algumas atualizações:
- As requisições realizadas pelos testes estavam apontando para a porta 8888, entretanto, o servidor roda na porta 80, que é a default do localhost, portanto eu alterei isso no código;
- Muitos testes necessitam de dados pré cadastrados no banco de dados, por exemplo "testar se o evento com id=3 existe", "verificar se usuário X consegue acessar o espaço Y". Para isso, vou elaborar um método para popular o banco de dados com alguns itens para testes, deletando-os ao final, além de deixar os métodos mais dinâmicos e independentes de ids e atributos fixos.

**Comment by LeonardoZanotti** [comment]
Após conversar com o Lucas, resolvemos deixar esta issue para um outro momento.

Já estou trabalhando nela há algum tempo e percebo que é bem desgastante e um tanto frustrante trabalhar nela.
Os testes propostos não parecem testar pontos cruciais da aplicação, sendo até meio irrelevantes para garantir o funcionamento correto do software.
Muitos testes são antigos e já não tem utilidade para o sistema atual.
Além disso, fornecer o devido suporte aos testes e corrigi-los para se adequar ao software pensado é uma tarefa que está tomando demasiado tempo e tendo um retorno desproporcionalmente desvantajoso.

Acredito que devessemos considerar simplesmente recriar todos os testes do zero, considerando apenas a aplicação atual em seu funcionamento. Seria mais organizado e seria possível uma visão mais completa sobre o que se está sendo testado, efetivamente.
