### ISSUE TITLE
Plano de trabalho (Monitoramento)

### ISSUE THREAD

**Issue by drabelodesign** [RedeMapas/mapas#543]
## *Objetivo*
Eu como Gestor Cultural
Quero criar os relatórios de plano de trabalho no formulário de inscrição, no momento de inscrição da oportunidade.
Para avaliar a proposta dos projetos.

## *Contexto*
Entendemos que foi importante interromper o fluxo ideal para que para o time conseguisse entregar o fluxo funcionando minimamente da etapa de Execução, que compreende as funcionalidades de configuração e monitoramento de relatório, plano de trabalho, prestação de contas e recurso. 

Essa atividade é uma adaptação da jornada utilizando as propostas do "fluxo ideal" utilizando a estrutura atual do Mapas.

## *Escopo de Design*

**Plano de Trabalho**
- [x] Gestor: Configuração e acompanhamento do Plano de Trabalho [Link](https://www.figma.com/design/HkR1qdfHPn4riffcBBOQwR/Prot%C3%B3tipos-%7C-Prioriza%C3%A7%C3%B5es?node-id=6237-82098&t=BZseVh0kuMCWn0Au-4)
- [x] Agente: painel de preenchimento e acompanhamento do Plano de Trabalho [Link](https://www.figma.com/design/HkR1qdfHPn4riffcBBOQwR/Prot%C3%B3tipos-%7C-Prioriza%C3%A7%C3%B5es?node-id=6256-59137&t=BZseVh0kuMCWn0Au-4)
- [x] Validação Uirá
- [x] Ajustes
- [x] Validação MinC.
- [ ] Ajustes finais

## *Critérios de Aceitação*
Dado que o Gestor Cultural precisa avaliar e acompanhar os plano de trabalho dos proponentes,
Quando ele está avaliando o mérito das oportunidades
Então é importante que ele possa ter um recurso de criação de plano de trabalho configurável e adaptável para cada tipo de oportunidade criada.
 

## *Observações*
[Link do fluxo](https://www.figma.com/design/HkR1qdfHPn4riffcBBOQwR/Prot%C3%B3tipos-%7C-Prioriza%C3%A7%C3%B5es?node-id=6237-52115&node-type=canvas&t=EfOwa5cySvdXsxpK-0)

**Comment by uira** [comment]
Duplicada da #534
