### ISSUE TITLE
[HOME] Atribuir tratamento de hiperlink para link do repositório na home.

### ISSUE THREAD

**Issue by emillecatarine** [RedeMapas/mapas#65]
**Contexto:** Na seção "Alô desenvolvedores", na home, existe o link "Conheça o repositório". Está em preto como as demais tipografias da tela, o que prejudica o entendimento de que se trata de um hiperlink.
**Ocorrência:** Desktop e mobile
**Recomendação:** Criar botão com o texto "Conheça o repositório" ou assumir tratamento de hiperlink para facilitar o entendimento do usuário.

<img width="1233" alt="image" src="https://github.com/LabCDBr/gestao/assets/95487110/08bd77e8-b431-4386-abc8-7c5c587d9a24">

**Comment by LeonardoZanotti** [comment]
![download](https://github.com/user-attachments/assets/30956bc0-6a62-4ebe-94a8-ec3b231919b5)

Botão criado e estilo atualizado para melhor identificação.

Pull request: FIX - update no estilo do botão de conheca o repositorio na Home #300
