### ISSUE TITLE
[HOME] Padronizar altura de perfis em destaque

### ISSUE THREAD

**Issue by emillecatarine** [RedeMapas/mapas#67]
**Contexto:** Na home, na seção "Em destaque", os cards dos perfis em destaque estão se adaptando à quantidade de conteúdo. O ideal, porém, seria que todos os cards tivessem a mesma altura.
**Ocorrência:** Desktop e mobile
Recomendação: Padronizar altura de todos os cards de acordo com a altura do card mais alto. Manter botões sempre alinhados na base do card.

Como está atualmente:
<img width="1143" alt="image" src="https://github.com/LabCDBr/gestao/assets/95487110/4044cf36-7483-4fa8-9cc7-d20e8bca5091">

Sugestão de melhoria:

![Image](https://github.com/LabCDBr/gestao/assets/95487110/c14fc537-0b0e-40a8-950a-ff7182c71ed3)

**Comment by lpirola** [comment]
As duas formas recomendadas de criar colunas estão descritas nesse link https://moderncss.dev/equal-height-elements-flexbox-vs-grid/

**Comment by lpirola** [comment]
@gabi-gandine poderia trazer alguma atualização sobre essa tarefa?

**Comment by papatrock** [comment]
Tanto na versão mobile quando de desktop os tamanhos estão padronizados, testei com descrição com tamanho máximo de caracteres (400) e também com tamanho mínimo, ambos funcionando como deveria. Código fonte está bem estruturado.

## Antes:


![Image](https://github.com/user-attachments/assets/c5d752a4-86cc-499d-9283-b4eaf6040da7)

## Depois:


![Image](https://github.com/user-attachments/assets/8c58e1e3-1cf7-4201-afa8-54ed2cf0d1d5)
