### ISSUE TITLE
[AGENTE] Feedback impreciso ao tentar cadastrar imagem com formato não aceito.

### ISSUE THREAD

**Issue by emillecatarine** [RedeMapas/mapas#69]
Contexto: Na foto de perfil do agente, tentei fazer o upload de uma foto no formato .webp. A plataforma me apresentou o disclaimer "Corrija os erros indicados". Não há, porém, qualquer indicação de que o erro é o formato da imagem.
Ocorrência: Desktop e mobile. 
Recomendação: Trocar mensagem do disclaimer para: "Formato de imagem inválido. Insira imagens nos formatos (listar formatos aceitos)."

<img width="400" alt="image" src="https://github.com/LabCDBr/gestao/assets/95487110/748d8dc9-f483-4513-a698-cda7ed0ff974">

**Comment by LeonardoZanotti** [comment]
Bug corrigido e pull request criado: #298 
 
Tentativa de upload de imagem .webp, retornando a mensagem de erro atualizada:
![名称未設定](https://github.com/user-attachments/assets/bce38b47-fc9d-47f8-9af2-163bdeba2281)
