### ISSUE TITLE
[AGENTE] Checkbox "Localização pública" é desmarcado ao salvar a edição.

### ISSUE THREAD

**Issue by emillecatarine** [RedeMapas/mapas#70]
**Contexto:** Na tela de edição de agente, quando marco o checkbox "Localização pública" e salvo as alterações, o checkbox é automaticamente desmarcado e, acima do mapa, segue a indicação "Sem endereço". O perfil fica de fato público, mas a desmarcação do campo e o texto "Sem endereço" deixa a impressão de que a ação não se concretizou.
**Ocorrência:** Desktop e mobile
**Recomendação:** Manter o campo marcado mesmo após o salvamento e remover o texto "Sem endereço" para agentes que tenham algum endereço cadastrado.

<img width="788" alt="image" src="https://github.com/LabCDBr/gestao/assets/95487110/29f3e8a0-3e17-4233-9d25-816a362ff638">

**Comment by enieber** [comment]
@emillecatarine comecei testar e não consegui identificar o problema, podera colocar mais detalhes sobre qual o usuario e tipo de usurio que foi feito o teste? Essas duas solicitações que foram colocadas de não mostrar "Sem endereço" já está acontecendo e a parte de salvar o checkbox também.

**Comment by Aushiffer** [comment]
O problema não está ocorrendo aqui. Quando se cria/edita um agente, o estado da checkbox persiste e o endereço aparece (quando o agente o possui).

**Comment by vicmagpac** [comment]
Em alinhamento com o desenvolvedor @Aushiffer  e baseado nos testes realizados não foram identificados problemas na task.
