### ISSUE TITLE
[AGENTES] Atuação na tela de agentes parece hiperlink.

### ISSUE THREAD

**Issue by emillecatarine** [RedeMapas/mapas#71]
**Contexto:** Na página de agentes, no card de cada agente há a informação do tipo de atuação do agente ("Esse agente atua de forma: Individual/Coletiva"), sendo que os termos "Individual" e "Coletiva" são apresentados na cor vermelha. Essa cor dá a entender que o texto é um hiperlink.
**Ocorrência:** Desktop e mobile.
**Recomendação:** Podem ser adotadas duas soluções: 1) Adicionar hiperlinks nos textos, realizando uma filtragem na busca de acordo com o filtro (hiperlink) selecionado – solução ideal; 2) Deixar o texto preto.

<img width="895" alt="image" src="https://github.com/LabCDBr/gestao/assets/95487110/077d8d67-ff05-4d64-9884-fed8f7dee85d">

**Comment by enieber** [comment]
Consigo alterar a cor do tipo de agente

**Comment by enieber** [comment]
Essa alteração precisa ser feita no thema

**Comment by enieber** [comment]
@emillecatarine Pelo que entendi todo tipo de agente fica com a cor laranja. E não tem um hiperlink, a ideia é que tenha um hiperlink no tipo da categoria?

**Comment by vicmagpac** [comment]
@emillecatarine no mapas, cada entidade tem sua cor por padrão. 

Oportunidades (laranja): 
![image](https://github.com/RedeMapas/mapas/assets/3487411/3ad65921-2de1-49a0-aa92-5cf6cc8769d0)

Agentes (laranja mais claro)
![image](https://github.com/RedeMapas/mapas/assets/3487411/3386b128-5228-4aad-9934-e32bcd6b5830)

Espaços (verde)

![image](https://github.com/RedeMapas/mapas/assets/3487411/31120a42-024a-41c3-8ea6-4d1fe2f7b776)

Projetos (azul)

![image](https://github.com/RedeMapas/mapas/assets/3487411/ba1d68e2-8543-4b8e-b308-41b0cb7f9ace)


Para deixar mais especificado para o dev que implementar a atividade, @emillecatarine a alteração solicitada deve ser apenas para a entidade agente ou para todas as entidades como consta nas imagens acima?

**Comment by uira** [comment]
@vicmagpac E esse aqui é um exemplo, @RaniGub, de atividade que possa ficar desnecessária com a interface de configuração
