### ISSUE TITLE
[PROJETOS] Na tela de detalhes do projeto, indicar quantidade de subprojetos vinculados.

### ISSUE THREAD

**Issue by emillecatarine** [RedeMapas/mapas#76]
**Contexto:** Na tela de detalhes do projeto existe a indicação de subprojetos vinculados. Apenas consigo visualizar a quantidade ao clicar e fazer a contagem manualmente.
**Ocorrência:** Desktop e mobile.
**Recomendação:** Incluir indicação da quantidade de subprojetos vinculados entre parêntesis ao lado do rótulo "Subprojetos":

<img width="1167" alt="image" src="https://github.com/LabCDBr/gestao/assets/95487110/0f890105-8e46-4902-ab65-b5a9281a8506">

**Comment by LeonardoZanotti** [comment]
![image](https://github.com/user-attachments/assets/efd840e1-ba04-469c-bf4a-1f4d42e13a69)

Resolvido, commit: https://github.com/RedeMapas/mapas/commit/c39713b4091bbc6f4007534e36cc07738da6bbeb
