### ISSUE TITLE
[PROJETOS] Tipos de projetos parecem hiperlinks.

### ISSUE THREAD

**Issue by emillecatarine** [RedeMapas/mapas#78]
**Contexto:** Na página de projetos, no card de cada projeto há a informação "TIPO", seguida do tipo do projeto na cor verde. Essa cor dá a entender que o texto é um hiperlink.
**Ocorrência:** Desktop e mobile.
**Recomendação:** Podem ser adotadas duas soluções: 1) Adicionar hiperlinks nos textos, realizando uma filtragem na busca de acordo com o filtro (hiperlink) selecionado – solução ideal; 2) Deixar o texto preto.

Como está:
<img width="500" alt="image" src="https://github.com/LabCDBr/gestao/assets/95487110/e1f0c014-8369-45b3-b56f-a3f4e745a9e1">

Sugestão:
- Caso seja possível/viáve; incluir hiperlinks nos textos de tipos de projetos (que resultam em uma filtragem pelo tipo selecionado), seguir nesse caminho. Caso não seja possível/viável, aplicar a seguinte solução:

![Image](https://github.com/LabCDBr/gestao/assets/95487110/5933d779-e637-4007-9bb4-6205ef30544f)

**Comment by LeonardoZanotti** [comment]
![image](https://github.com/user-attachments/assets/f74502eb-1098-4447-ad6b-1529d9ed2ef1)

Solução já implementada previamente.
