### ISSUE TITLE
[AGENTE] Botão "criar agente" não retorna resultado

### ISSUE THREAD

**Issue by emillecatarine** [RedeMapas/mapas#82]
**Contexto:** No perfil do admin, tanto na página "Agentes" quanto na seção "Meus agentes" no Painel de controle, o clique no botão "Criar Agente" não retorna nenhum resultado.
**Ocorrência:** Desktop e mobile
**Recomendação:** Corrigir bug. O clique no botão "Criar Agente", em qualquer página e em qualquer perfil, deve abrir a modal de criação de novo agente.

**Comment by LeonardoZanotti** [comment]
![image](https://github.com/user-attachments/assets/b2eca97e-ae22-4dfb-8de5-85f7d87cff9e)
![image](https://github.com/user-attachments/assets/0cb8b9d3-e80b-42f8-bebe-76c9a98fa441)

Não consegui replicar o bug.

@emillecatarine pode me dar mais informações e me confirmar se o bug continua ocorrendo por gentileza?
